/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bylofefjrwvytskcivit"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bG9mZWZqcnd2eXRza2Npdml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxNzcwMTAsImV4cCI6MjA4MDc1MzAxMH0.ERDZKy1f00sW9Bg-2pY-wDt_VfHrtyaC7wz4DyetXjM"